<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NhapKhoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nhap_khos')->delete();

        DB::table('nhap_khos')->truncate();

        DB::table('nhap_khos')->insert([
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-10 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  1,
                'ten_san_pham'      =>  'Tủ lạnh Sharp Inverter 150 lít SJ-X176E-SL',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-13 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  1,
                'ten_san_pham'      =>  'Tủ lạnh Sharp Inverter 150 lít SJ-X176E-SL',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-13 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  2,
                'ten_san_pham'      =>  'Tủ lạnh Sharp Inverter 572 lít SJ-FX640V-SL',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-13 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  2,
                'ten_san_pham'      =>  'Tủ lạnh Sharp Inverter 572 lít SJ-FX640V-SL',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-16 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  2,
                'ten_san_pham'      =>  'Tủ lạnh Sharp Inverter 572 lít SJ-FX640V-SL',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-17 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  3,
                'ten_san_pham'      =>  'Tủ lạnh Samsung Inverter 276 lít RB27N4170BU/SV',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-22 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  4,
                'ten_san_pham'      =>  'Máy lạnh tủ đứng LG Inverter 3 HP ZPNQ30GR5E0',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-24 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  4,
                'ten_san_pham'      =>  'Máy lạnh tủ đứng LG Inverter 3 HP ZPNQ30GR5E0',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-24 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  6,
                'ten_san_pham'      =>  'Máy lạnh Panasonic Inverter 1 HP CU/CS-XU9ZKH-8',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-24 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  7,
                'ten_san_pham'      =>  'Máy giặt Panasonic Inverter 9.5 Kg NA-V95FC1LVT',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-05-29 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  7,
                'ten_san_pham'      =>  'Máy giặt Panasonic Inverter 9.5 Kg NA-V95FC1LVT',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-02 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  7,
                'ten_san_pham'      =>  'Máy giặt Panasonic Inverter 9.5 Kg NA-V95FC1LVT',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-10 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  7,
                'ten_san_pham'      =>  'Máy giặt Panasonic Inverter 9.5 Kg NA-V95FC1LVT',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-12 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  10,
                'ten_san_pham'      =>  'Nồi cơm điện tử Toshiba 1.8 lít RC-18DR2PV(K)',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-18 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  9,
                'ten_san_pham'      =>  'Tủ chăm sóc quần áo thông minh LG S5GOC',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-18 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  11,
                'ten_san_pham'      =>  'Máy xay sinh tố Smeg BLF01CREU (535.43.635)',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-19 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  12,
                'ten_san_pham'      =>  'Bình đun siêu tốc Delonghi 1.7 lít KBOV2001.GR',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  1,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-20 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  12,
                'ten_san_pham'      =>  'Bình đun siêu tốc Delonghi 1.7 lít KBOV2001.GR',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  2,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-20 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  14,
                'ten_san_pham'      =>  'Quạt sạc điện Kangaroo KG738',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  2,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-20 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  15,
                'ten_san_pham'      =>  'Quạt trần KDK DC inverter U60FW(SIL)',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  2,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-20 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  15,
                'ten_san_pham'      =>  'Quạt trần KDK DC inverter U60FW(SIL)',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  2,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  15,
                'ten_san_pham'      =>  'Quạt trần KDK DC inverter U60FW(SIL)',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  2,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  16,
                'ten_san_pham'      =>  'Máy lọc nước RO Sunhouse SHA8889K 9 lõi',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  2,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  17,
                'ten_san_pham'      =>  'Máy lọc nước ion kiềm Fuji Smart i9 10 tấm điện cực',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  2,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  18,
                'ten_san_pham'      =>  'Máy lọc nước UF IONPIA ION-UFS4P 4 lõi',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  3,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  21,
                'ten_san_pham'      =>  'Điện thoại Samsung Galaxy S23 Ultra 5G 256GB',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  3,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  22,
                'ten_san_pham'      =>  'Điện thoại iPhone 14 Pro Max 128GB',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  3,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  23,
                'ten_san_pham'      =>  'Điện thoại OPPO Reno7 Z 5G',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  4,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  24,
                'ten_san_pham'      =>  'Laptop Asus Gaming TUF Dash F15',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  4,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-21 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  25,
                'ten_san_pham'      =>  'Laptop Apple MacBook Air 13 inch M2 2022)',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  4,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-22 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  26,
                'ten_san_pham'      =>  'Laptop Lenovo Legion 5 15IAH7',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  4,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-22 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  27,
                'ten_san_pham'      =>  'Điện thoại Samsung Galaxy S23 Ultra 5G 256GB',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  4,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-22 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  28,
                'ten_san_pham'      =>  'Điện thoại iPhone 14 Pro Max 128GB',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  4,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-22 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  29,
                'ten_san_pham'      =>  'Điện thoại OPPO Reno7 Z 5G',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
            [
                'id_partner'        =>  4,
                'ma_phieu_nhap'     =>  'PNK' . (24062013 + rand(1, 1000)),
                'ngay_nhap'         =>  Carbon::parse('2023-06-22 10:30:00')->format('Y-m-d H:i:s'),
                'id_san_pham'       =>  30,
                'ten_san_pham'      =>  'Máy giặt Panasonic Inverter 9.5 Kg NA-V95FC1LVT',
                'so_luong_nhap'     =>  $so_luong_nhap = rand(1, 20),
                'don_gia_nhap'      =>  $don_gia_nhap = rand(1000, 4000000),
                'thanh_tien_nhap'   =>  $so_luong_nhap * $don_gia_nhap,
            ],
        ]);
    }
}
